version: '3.4'

networks:
    myAppNetwork: 

services:
  SqlServerDb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
        - 8002:1433
    environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=dy3U]ha6CjD*4k*
        - MSSQL_PID=Express
  api:
    container_name: api
    image: ${DOCKER_REGISTRY-}api
    ports:
        - 8001:80 
    build:
      context: .
      dockerfile: API/Dockerfile
    depends_on:
        - SqlServerDb
